### ISSUE TITLE
SQL Server Driver Roadmap

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-mssql#69]
This ticket collects the roadmap for the next few releases. It's meant as aggregator and reference.

## M8 release

* [x] Consider large chunks in StreamDecoder #63 (alternatively M9)
* [x] Implement RowMetadata.getColumnNames() #64

## RC1 release

* [x] Add FluxDiscardOnCancel to clear wire protocol state on `cancel()` signal, see #11 
* [x] Add benchmark suites #68

## GA release

**Comment by mp911de** [comment]
Closing, as the GA version was released. All the further items we like to include in the driver are available from the general backlog in GitHub issues.
